#!/usr/bin/env python
import os, sys
import ROOT
ROOT.PyConfig.IgnoreCommandLineOptions = True
from importlib import import_module
from PhysicsTools.NanoAODTools.postprocessing.framework.postprocessor import PostProcessor
from PhysicsTools.NanoAODTools.postprocessing.modules.common.puWeightProducer import *
from PhysicsTools.NanoAODTools.postprocessing.modules.common.PrefireCorr import PrefCorr

fnames=[
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_1-1.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_1-2.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_1-3.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_1-4.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_1.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_10.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_100.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_101.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_102.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_103.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_104.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_105.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_106.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_107.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_108.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_109.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_11.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_110.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_111.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_112.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_114.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_115.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_116.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_117.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_118.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_119.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_12.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_120.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_121.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_122.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_123.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_124.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_125.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_126.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_127.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_128.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_129.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_13.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_130.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_131.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_132.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_133.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_134.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_135.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_136.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_14.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_15.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_16.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_17.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_18.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_19.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_2.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_20.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_21.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_22.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_23.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_24.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_25.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_26.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_27.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_28.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_29.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-1.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-10.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-11.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-2.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-3.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-4.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-5.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-6.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-7.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-8.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3-9.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_3.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_30.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_31.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_32.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_33.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_34.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_35.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_36.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_37.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_38.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_39.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_4.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_40.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_41.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_42.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_43.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_44.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_45.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_46.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_47.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_48.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_49.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_5.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_50.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_51.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_52.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_53.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_54.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_55.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_56.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_57.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_58.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_59.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_6.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_60.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_61.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_62.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_63.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_64.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_65.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_66.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_67.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_68.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_69.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_7.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_70.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_71.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_72.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_73.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_74.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_75.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_76.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_77.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_78.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_79.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_8.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_80.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_81.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_82.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_83.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_84.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_85.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_86.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_87.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_88.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_89.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_9.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_90.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_91.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_92.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_93.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_94.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_95.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_96.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_97.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_98.root',
'/mnt/hadoop/user/uscms01/pnfs/unl.edu/data4/cms/store/user/juwillia/DoubleEG/Run2017D/myNanoProdData_NANO_99.root',
]

# 2017 MC
#p=PostProcessor(".",fnames,"HLT_DoublePhoton70 == 1","keep_drop.txt",[puAutoWeight_2017(),PrefCorr()],provenance=True,haddFileName="nanoAOD_aqgc2017_Skim.root")

# 2017 Data
p=PostProcessor(".",fnames,"HLT_DoublePhoton70 == 1","keep_drop.txt",[],provenance=True,haddFileName="nanoAOD_Run2017D_Old_Skim.root")

# 2018 MC
#p=PostProcessor(".",fnames,"HLT_DoublePhoton70 == 1","keep_drop.txt",[puAutoWeight_2018()],provenance=True,haddFileName="nanoAOD_tt2018_test_Skim.root")

# 2018 Data
#p=PostProcessor(".",fnames,"HLT_DoublePhoton70 == 1","keep_drop.txt",[],provenance=True,haddFileName="nanoAOD_dataTest_Skim.root")

p.run()
